spring:
  application:
    name: api-gateway
server:
  port: 8765

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 20000

zuul:
  routes:
    quotes:
      service-id: ms-quotes
      path: /ms-quotes/**
    consumer:
      service-id: q-consumer
      path: /q-consumer/**

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG