spring:
  application:
    name: ms-discover
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

opentracing:
  jaeger:
    udp:
      sender:
        host: localhost #udp host for sender. By default Jaeger libraries use a UDP sender to report finished spans to the jaeger-agent daemon
        port: 6831 # udp port
    log-spans: true #logs the spans in console